### PR TITLE
Event Loop Driver Prototype

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Prototype based upon discussion here: https://github.com/async-interop/event-loop/issues/1

### CODE REVIEW

**Comment by assertchris** [comment]
I wanted to say, in #1 (though that's closed now) that I also prefer `once`/`repeat` over `timer`/`periodic`. Other than that, I agree with @WyriHaximus and @trowski comments. :)

**Comment by AndrewCarterUK** [comment]
@WyriHaximus / @trowski / @assertchris 

Can one of you guys have a check over this PR and merge if you're happy with it.

This is by no means a finished product - but an early draft based upon the discussions we've had in the issues. Where an issue hasn't been closed (or parties haven't reached a full agreement) I've gone with my interpretation of which of the suggested approaches is "best", based upon the discussion that has been had.

Hopefully merging this PR as an early prototype will allow for incremental development and give us some reference point for other features that need to be added.

**Comment by AndrewCarterUK** [comment]
re-ping @WyriHaximus @trowski @assertchris

**Comment by kelunik** [comment]
LGTM. You might want to squash the commits into a single one, don't know.

**Comment by assertchris** [comment]
I like it. Good job.

**Comment by WyriHaximus** [comment]
I also like it :+1:

**Comment by kelunik** [comment]
Could someone of you then go ahead and merge it?

**Comment by kelunik** [comment]
Missing reactions for the merge event. :smile:

**Pull request merged**
