### PR TITLE
Add driver interfaces for lower level access

### PR DESCRIPTION
**Pull request by kelunik**
PR for #16.

### CODE REVIEW

**Comment by assertchris** [comment]
I don't understand the need for these. In my mind, `LoopDriver` should be the lowest interface defined. Could you elaborate on the need for them?

**Comment by kelunik** [comment]
They're required for primitives like filesystem access: https://github.com/amphp/file/blob/master/lib/UvDriver.php

**Comment by assertchris** [comment]
Mentioned here (I think): https://github.com/async-interop/event-loop/issues/16

**Comment by kelunik** [comment]
Right, the description already includes a link to #16.

**Comment by trowski** [comment]
-1 on having interfaces for specific implementations. Interfaces should be tied to the features that could be supported. See https://github.com/async-interop/event-loop/issues/16#issuecomment-219310539.

**Comment by AndrewCarterUK** [comment]
I'm -1 here

**Comment by coderstephen** [comment]
Another -1 here... this seems like a step in the wrong direction to me.

**Pull request closed without merging**
