### PR TITLE
Fix code markdown for Loop::info

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by bwoebi** [comment]
What's the _fix_ here? I.e. why does this need to be indented by four chars??

**Comment by kelunik** [comment]
Because PHPDoc is supposed to be markdown and it's supposed to be formatted as code in docs.

**Comment by kelunik** [comment]
If it's not formatted as code, any markdown parser will show it like that:

image

**Comment by kelunik** [comment]
See #103.

**Pull request closed without merging**
