### PR TITLE
Improve enable() doc and mention it also in the class level phpdoc block

### PR DESCRIPTION
**Pull request by kelunik**
Thanks @nrk for mentioning it again.

### CODE REVIEW

**Comment by nrk** [comment]
Correct me if I'm wrong, but the behaviour of `onReadable()`, `onWritable()` and such methods still seems kind of vague to me. I think it should be stated clearly in their docs if the watcher being returned is already enabled by the driver or the underlying implementation (e.g. no need for the user to call `enable()` after `onReadable()`) or not.

**Comment by kelunik** [comment]
I can add a note to everything that creates a watcher, too.

**Review by bwoebi — APPROVED** [review]

**Comment by WyriHaximus** [comment]
The current changes make the default behavior a lot clearer but also adding a note to everything that creates a watcher is a good idea :+1:

**Comment by nrk** [comment]
@kelunik IMHO simply specifying that "_Watchers created by this method MUST be immediatly marked as enabled._" (or something along these lines) in the phpdocs of `onWritable()`, `onReadable()`, `onSignal()`, `defer()`, `delay()`, `repeat()` is more than enough.

This is actually different from the behaviour described for `enable()`, which tells how the driver should act when enabling a watcher.

**Comment by kelunik** [comment]
@nrk I've added a note to every method creating a watcher and have clarified `enable` and `disable`.

**Review by WyriHaximus — APPROVED** [review]

**Comment by kelunik** [comment]
Ready to merge?

**Pull request merged**
