### PR TITLE
Eliminate Registry trait

### PR DESCRIPTION
**Pull request by trowski**
Moves the functionality of the Registry trait directly into Loop.

### CODE REVIEW

**Comment by trowski** [comment]
@assertchris Can you elaborate on the reasons for having this in a separate trait?

**Comment by bwoebi** [comment]
I see clear advantages here. The main API is reduced to a single file. Look this single file up and you know everything about the Loop you need.
Otherwise it's potentially easy to even miss the "Registry" trait use there at the top...

But perhaps there's something I don't see? \cc @assertchris

**Comment by WyriHaximus** [comment]
Sharing the interested in why this is in a trait

**Comment by bwoebi** [comment]
Deferring this until it's clear how we can handle cases like https://github.com/async-interop/event-loop/pull/65#discussion_r64792576

**Comment by assertchris** [comment]
Sorry for the delay. My only concern here is SRP. Trait is more efficient than a registry object dependency, but that would be my other suggestion. Composing a registry or having the code in a trait...

**Comment by bwoebi** [comment]
That's not important for now @assertchris as we anyway need to solve #68 first

**Comment by assertchris** [comment]
I know it's related to other stuff. A couple folks asked for my reasoning, which is what I provided.

**Comment by bwoebi** [comment]
Fine then …

But IMO a trait does not solve anything related to SRP. It just makes the code reside in a different file. The class is still providing _functions_ (even if indirectly via compile-time trait C&P).
A registry object dependency won't solve it either, the Loop class will still have to provide access functions to something not really related: a storage.

**Comment by bwoebi** [comment]
Closing as #68 has been merged.

**Pull request closed without merging**
