### PR TITLE
Make use of PHP 7 features

### PR DESCRIPTION
**Pull request by kelunik**
Adds scalar type declarations and return type declarations. Increases the minimum version of PHP to 7.0.0.

We can discuss whether we make the error handler an interface now, as we have anonymous classes.

Relates to #2.

### CODE REVIEW

**Comment by kelunik** [comment]
Does anybody know the current state of PHP 7 features implemented in HHVM? Do we care about HHVM?

**Comment by WyriHaximus** [comment]
> Does anybody know the current state of PHP 7 features implemented in HHVM? Do we care about HHVM?

HHVM doesn't expose itself to as PHP 7 to composer table flips when you try to run composer install on it. Didn't go any further and pretty much dropping HHVM from my PHP 7 only package over the last months because of that. No idea what PHP 7 features they would support

**Comment by bwoebi** [comment]
Can you please PR the fixes separately (like detatch => detach, $time => $msDelay etc.)?

**Comment by kelunik** [comment]
Closing as of https://github.com/async-interop/event-loop/issues/2#issuecomment-269646468.

**Pull request closed without merging**
